repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        types_or: [python, pyi, jupyter]
        language: system
        entry: ruff check --fix

      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi, jupyter]