
line-length = 120
indent-width = 4


[lint]

select = ["F", "E", "W", "I"]
ignore = ["E203", "E266", "E501"]


fixable = ["ALL"]
unfixable = ["F401"]


[format]
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"