name: Publish Allure Report
on: [push]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest allure-pytest

      - name: Run tests
        run: |
          pytest || true

      - name: Setup Allure CLI
        uses: eroshenkoam/allure-cli-action@v1
        with:
          version: 2.27.0

      - name: Install Allure
        run: |
          sudo apt-get install -y curl
          curl -o allure-2.24.1.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
          tar -zxvf allure-2.24.1.tgz
          sudo mv allure-2.24.1 /opt/allure
          echo "/opt/allure/bin" >> $GITHUB_PATH
          allure --version

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report